[server]
headless = true
port = 8501                # <--- Must match AWS Nginx default
address = "0.0.0.0"        # <--- Crucial: Listen to all traffic, not just localhost
enableCORS = false         # <--- Fixes "Network Error" / 403 Forbidden
enableXsrfProtection = false # <--- Fixes "Black Screen" / Connection Refused

[theme]
base = "dark"

[browser]
gatherUsageStats = false   # <--- Prevents unnecessary pinging to Streamlit servers
